# Generated by Django 5.2.3 on 2025-06-18 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_variant'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('new_customers', models.PositiveIntegerField(default=0)),
                ('returning_customers', models.PositiveIntegerField(default=0)),
                ('total_customers', models.PositiveIntegerField(default=0)),
                ('retention_rate', models.FloatField(default=0.0, help_text='Percentage of returning customers')),
                ('average_customer_lifetime_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Customer Analytics',
            },
        ),
        migrations.CreateModel(
            name='SalesAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_usage_count', models.PositiveIntegerField(default=0)),
                ('discount_total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sales Analytics',
            },
        ),
        migrations.CreateModel(
            name='WebsiteTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0.0, help_text='Percentage of single-page visits')),
                ('average_session_duration', models.FloatField(default=0.0, help_text='Average time spent per session in seconds')),
                ('top_referral_source', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Website Traffic',
            },
        ),
        migrations.CreateModel(
            name='MarketingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('impressions', models.PositiveIntegerField(default=0, help_text='Number of times campaign/discount was shown')),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0, help_text='Number of purchases attributed to campaign/discount')),
                ('click_through_rate', models.FloatField(default=0.0, help_text='Percentage of impressions leading to clicks')),
                ('conversion_rate', models.FloatField(default=0.0, help_text='Percentage of clicks leading to conversions')),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='promotions.promotion')),
            ],
            options={
                'verbose_name_plural': 'Marketing Analytics',
                'constraints': [models.CheckConstraint(condition=models.Q(('campaign__isnull', False), ('discount_code__isnull', False), _connector='OR'), name='at_least_one_marketing_identifier')],
                'unique_together': {('campaign', 'discount_code', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('add_to_cart_count', models.PositiveIntegerField(default=0)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0, help_text='Percentage of views leading to purchase')),
                ('abandonment_rate', models.FloatField(default=0.0, help_text='Percentage of add-to-cart not leading to purchase')),
                ('stock_turnover_rate', models.FloatField(default=0.0, help_text='Rate at which stock is sold and replaced')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Analytics',
                'unique_together': {('product', 'date')},
            },
        ),
    ]
