# Generated by Django 5.2.3 on 2025-06-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='newsletter_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='promotional_emails',
            field=models.BooleanField(default=False),
        ),
    ]
