# Generated by Django 5.2.3 on 2025-06-18 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('api_key', models.CharField(blank=True, help_text='API key for the platform', max_length=255)),
                ('api_secret', models.CharField(blank=True, help_text='API secret for the platform', max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='Is the integration active?')),
            ],
            options={
                'verbose_name': 'Social Platform',
                'verbose_name_plural': 'Social Platforms',
            },
        ),
        migrations.CreateModel(
            name='ProductSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, help_text='External ID on the social platform', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_syncs', to='products.product')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_products', to='social_integration.socialplatform')),
            ],
            options={
                'verbose_name': 'Product Sync',
                'verbose_name_plural': 'Product Syncs',
                'constraints': [models.UniqueConstraint(fields=('product', 'platform'), name='unique_product_platform')],
            },
        ),
    ]
