# Generated by Django 5.2.3 on 2025-06-17 01:35

from django.db import migrations, models
import django.db.models.deletion

def set_shipping_address_to_null(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Order.objects.all().update(shipping_address=None)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shippingaddress'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_shipping_address_to_null),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_delivery_days', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Shipping Methods',
            },
        ),
        migrations.AlterField(
            model_name='Order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.shippingaddress'),
        ),
        migrations.AddField(
            model_name='Order',
            name='shipping_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.shippingmethod'),
        ),
    ]
