# Generated by Django 5.2.3 on 2025-06-17 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_shippingmethod_alter_order_shipping_address_and_more'),
    ]

    operations = [
    ]
