# Generated by Django 5.2.3 on 2025-06-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='Stores Stripe PaymentIntent ID for payment processing', max_length=255, null=True),
        ),
    ]
