# Generated by Django 5.2.3 on 2025-06-17 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Variant name (e.g., 'Red', 'Large')", max_length=100)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0.0, help_text='Price difference from base product', max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit identifier', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Variants',
                'unique_together': {('product', 'name')},
            },
        ),
    ]
